front: env RECIPE_APP=127.0.0.1:3001 bundle exec rackup fron_app_config.ru -o 127.0.0.1 -p 3000
recipe: bundle exec rackup recipe_app_config.ru -o 127.0.0.1 -p 3001
agent: socat UDP-RECVFROM:2000,fork STDOUT
